name: codebase_echo
description: Port of official Laravel Echo package for your Flutter apps.
version: 1.0.0
homepage: https://github.com/codebase-eu/echo

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
